### PR TITLE
Usage example with Webpack 2 is added.

### PR DESCRIPTION
**Pull request by ezze**

### CODE REVIEW

**Comment by kisenka** [comment]
Cool, thanks!

**Comment by kisenka** [comment]
@ezze does it works with Webpack 2? :)

**Comment by ezze** [comment]
@kisenka, yes, it does. I upgraded my project from Webpack 1 to Webpack 2 today and it works fine when resolving from both sass and JS code. The only major change I had to do is to move query part `?fill=` of loader's regular expression to `resourceQuery`. Otherwise [this condition](https://github.com/webpack/webpack/blob/3855b77275d4de0ff23b8c83ef3b8ad43fef00dc/lib/RuleSet.js#L391-L392) is not passed. Have you any issues with it?

I have something like this in my Webpack config:

```
const NODE_ENV = process.env.NODE_ENV === 'production' ? 'production' : 'development';
const NO_EXTRACT = !!process.env.NO_EXTRACT;
const THEME = process.env.THEME ? process.env.THEME : 'cyan';

const sassLoader = [{
        loader: 'css-loader',
        options: {
            discardComments: {
                removeAll: true
            }
        }
    },
    'postcss-loader',
    'svg-fill-loader/encodeSharp', {
        loader: 'resolve-url-loader',
        options: {
            keepQuery: true
        }
    }, {
        loader: 'sass-loader',
        options: {
            sourceMap: true,
            data: `$theme: "${THEME}"`
        }
    }
];

const sassRule = {
    test: /\.(sass|scss)$/,
    use: NO_EXTRACT ? ['style-loader'].concat(sassLoader) : ExtractTextPlugin.extract({
        use: sassLoader,
        fallback: "style-loader",
        publicPath: '../'
    }),
    include: [
        path.resolve(__dirname, 'src')
    ]
};

const svgFillRule = {
    test: /\.svg$/,
    resourceQuery: /^\?fill=/,
    use: [
        'file-loader?name=img/vector/[name].[hash:6].[ext]',
        'svg-fill-loader'
    ]
};

const config = {
    module: {
        rules: [
            ...
            sassRule,
            svgFillRule
        ]
    },
    ...
}'

...

if (!NO_EXTRACT) {
    config.plugins.push(new ExtractTextPlugin({
        filename: 'css/[name].' + (NODE_ENV === 'development' ? '' : '[chunkhash:6].') + 'css',
        allChunks: true
    }));
}

export default config;
```

**Comment by kisenka** [comment]
> Do you have any issues with it?
No, I am on webpack 1 now, but planning to upgrade soon, so your experience is helpful.

> I have something like this in my Webpack config:
Oh my, looking like programming in configuration! :)

**Comment by ezze** [comment]
> Oh my, looking like programming in configuration! :)

Loader rules were splitted for easier excluding by commenting during the migration. Now they look better. Thanks. :)

**Pull request merged**
